# Generated by Django 5.1.1 on 2024-11-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_user1_alter_customuser_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user1',
            name='id',
        ),
        migrations.AlterField(
            model_name='user1',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
