# Generated by Django 5.1.1 on 2024-11-15 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_remove_user1_id_alter_user1_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_model',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('new_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='user1',
            old_name='name',
            new_name='Name',
        ),
    ]
